config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'submit', to: 'pages#submit'
  resources :mutations, only: [:show, :index] #only use show +index  action
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mutation.rb
class Mutation < ApplicationRecord
    validates :mutation, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mutations_controller.rb
class MutationsController < ApplicationController
def show
    @mutation = Mutation.find(params[:id])
end

def index
    @mutation = Mutation.all
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def submit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Given the name of an isoform, return the css class that the isoform badge should be
  def isoform_class(isoform)
    case isoform
    when 'KIF5A'
      'bg-kif5a'
      #'bg-info'
    when 'KIF5C'
      'bg-kif5c'
    when 'KHC'
      'bg-khc'
    else
      'bg-secondary'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kinesin Mutation Database</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- bootstrap table css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- bootstrap table js -->
    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/tableExport.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/libs/jsPDF/jspdf.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.0/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/export/bootstrap-table-export.min.js"></script>

    <script src="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/addrbar/bootstrap-table-addrbar.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/toolbar/bootstrap-table-toolbar.min.js"></script>
 
    <script src="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/print/bootstrap-table-print.min.js"></script>
    <!-- <script src="https://unpkg.com/bootstrap-table@1.20.2/dist/bootstrap-table-locale-all.min.js"></script> -->
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="/images/12t.png" alt="" width="30" height="30" class="d-inline-block align-text-top">
          Kinesin Database
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link active' %>
            </li>
            <li class="nav-item">
              <%= link_to 'About', about_path, class: 'nav-link' %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Data
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to 'KIF5A', mutations_path(search: "KIF5A"), class: 'dropdown-item', id:"fire1"  %> </li>
                <li><%= link_to 'KIF5C', mutations_path(search: "KIF5C"), class: 'dropdown-item', id:"fire2"%> </li>
                <li><%= link_to 'KHC', mutations_path(search: "KHC"), class: 'dropdown-item', id:"fire3"%> </li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <%= link_to 'Show All Mutations', mutations_path, class: 'dropdown-item', id:"fire4" %>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <%= link_to 'Submit', submit_path, class: 'nav-link' %>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="page-footer fixed-bottom font-small bg-light">
      <div class="footer-copyright text-center py-3">© 2022 Copyright: All Rights Reserved
        <a href="/"> </a>
      </div>
    </footer>

</body>
</html>

app/views/mutations/index.html.erb
<h1 class="my-3" id="header"></h1>

<div class="table-responsive">
    <table class='bootstrap-table table table-hover table-bordered'
           data-toggle="table"
           data-search="true"
           data-id-table="advancedTable"
           data-height="750"
           data-show-columns="true"
           data-pagination="true"
           data-page-size="100"
           data-page-list="[100,200]"
           data-single-select="true"
           data-show-print="true"
           data-show-export="true"
           data-export-data-type="all"
           data-addrbar="true"
           data-filter-control-multiple-search="true"
           data-advanced-search="true"
           data-toolbar="#toolbar">
        <thead class="table-light">
            <tr>
                <th data-field="mutation"  data-force-export="true">Mutation</th>
                <th data-field="isoform" data-sortable="true" data-force-export="true">Isoform</th>
                <th data-field="domain" data-sortable="true" data-force-export="true">Domain</th>
                <th data-field="species" data-sortable="true" data-force-export="true">Species</th>
                <th data-field="presentation" data-sortable="true" data-force-export="true">Presentation</th>
                <th data-field="year" data-sortable="true" data-force-export="true">Year</th>
                <th data-field="inheritance" data-sortable="true" data-visible="false" data-force-export="true">Inheritance</th>
                <th data-field="mutation_type" data-sortable="true" data-visible="false" data-force-export="true">Mutation Type</th>
                <th data-field="families_affected" data-sortable="true" data-visible="false" data-force-export="true">Families Affected</th>
                <th data-field="age_of_onset" data-sortable="true" data-visible="false" data-force-export="true">Age of Onset</th>
                <th data-field="reference" data-sortable="true" data-visible="false" data-force-export="true">Reference</th>
                <th data-field="URL" data-sortable="true" data-visible="false" data-force-export="true">URL</th>
                <th data-force-hide="true">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @mutation.each do |mutation| %>
                <tr>
                    <td><%= mutation.mutation %></td>
                    <td>
                        <span class="badge rounded-pill <%= isoform_class(mutation.isoform) %>"><%= mutation.isoform %></span>
                    </td>
                    <td><%= mutation.domain %></td>
                    <td><%= mutation.species %></td>
                    <td><%= mutation.presentation %></td>
                    <td><%= mutation.year %></td>
                    <td><%= mutation.inheritance %></td>
                    <td><%= mutation.mutation_type %></td>
                    <td><%= mutation.families_affected %></td>
                    <td><%= mutation.age_of_onset %></td>
                    <td><%= mutation.reference %></td>
                    <td><%= mutation.url %></td>
                    <td><%= link_to 'Show Details', mutation_path(mutation), class: 'btn btn-secondary btn-sm' %>  <a class="btn btn-secondary btn-sm" href= <%= mutation.url %> target="_blank" >URL</a> </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

<script>
var $table = $('#table')

  $(function() {
    $('#table').bootstrapTable()
  })
<!-- script for exporting data -->
  $(function() {
    $('#toolbar').find('select').change(function () {
      $table.bootstrapTable('destroy').bootstrapTable({
        exportDataType: $(this).val(),
        exportTypes: ['json', 'xml', 'csv', 'txt', 'sql', 'excel', 'pdf'],
        // columns: [
        //   {
        //     field: 'mutation',
        //     title: 'Mutation'
        //   },
        //   {
        //     field: 'isoform',
        //     title: 'Isoform'
        //   }, 
        //   {
        //     field: 'domain',
        //     title: 'Domain'
        //   }, 
        //   {
        //     field: 'species',
        //     title: 'Species'
        //   },
        //   {
        //     field: 'presentation',
        //     title: 'Presentation'
        //   },
        //   {
        //     field: 'year',
        //     title: 'Year'
        //   }
        // ]
      })
    }).trigger('change')
  })

  var header = "Show All Mutations"
  document.getElementById("header").textContent = header
  if (url.searchParams.has("KIF5A")) {
    var header = "Show All KIF5A Mutations";
    document.getElementById("header").textContent = header;
  }
  

  </script>

app/views/mutations/show.html.erb
<h1 class="my-4"> Expanded Mutation Details </h1>

<p><strong>Mutation: </strong> <%= @mutation.mutation %> </p>
<p><strong>Isoform: </strong><%= @mutation.isoform %> </p>
<p><strong>Domain: </strong><%= @mutation.domain %> </p>
<p><strong>Presentation: </strong><%= @mutation.presentation %> </p>
<p><strong>Category: </strong><%= @mutation.category %> </p>
<p><strong>Residue: </strong><%= @mutation.residue %> </p>
<p><strong>From: </strong><%= @mutation.from %> </p>
<p><strong>To: </strong><%= @mutation.to %> </p>
<p><strong>Inheritance: </strong><%= @mutation.inheritance %> </p>
<p><strong>Mutation Type: </strong><%= @mutation.mutation_type %> </p>
<p><strong>Year: </strong><%= @mutation.year %> </p>
<p><strong>Species: </strong><%= @mutation.species %> </p>
<p><strong>Families Affected: </strong><%= @mutation.families_affected %> </p>
<p><strong>Age of Onset: </strong><%= @mutation.age_of_onset %> </p>
<p><strong>Reference: </strong><%= @mutation.reference %> </p>
<p><strong>URL: </strong><a href= <%= @mutation.url %> target="_blank" ><%= @mutation.url %></a> </p>


<p>
    <%= link_to "Return to index", mutations_path, class: 'btn btn-secondary btn-sm' %>
</p>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1> About </h1>
    
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en-GB">
  <head>
    <meta charset="utf-8">
    <meta name="author" content="Ashleigh Davey">
    <title>Kinesin Mutations Database</title>
  </head>
  <body>
  <p>
  </p>
  <p>
  </p>
  
    <h1> Kinesin Mutations Database </h1>
    <h2>Homepage</h2>
    <p>Some other stuff goes here</p>
  </body>
</html>

app/views/pages/submit.html.erb
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeMPZZQSb3NVAd9YThRvxRvMU1EOaLIQ166_GQtgq1MwB-qJw/viewform?embedded=true" width="100%" height="750" frameborder="0" marginheight="0" marginwidth="0" class="mt-4">Loading…</iframe>